spring.application.name=Taeha


# ==========================================
# CONEXIÓN A MYSQL (AIVEN CLOUD)
# ==========================================

spring.datasource.url=jdbc:mysql://moises-moisesmolinacrispin6-d2cc.a.aivencloud.com:17141/defaultdb?useSSL=true&serverTimezone=America/Lima&allowPublicKeyRetrieval=true&ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_aJlwNij72ZRd_cjsq7a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================

# Usar 'validate' para proteger la estructura y datos ya importados en Aiven
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# THYMELEAF
# ==========================================

spring.thymeleaf.cache=false


# ==========================================
# SERVIDOR Y ARCHIVOS
# ==========================================

server.port=8080

app.upload.dir=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
